/*
 *   Copyright 2009 Jerome Avondo. All rights reserved.
 *   Use is subject to license terms supplied in LICENSE.txt
 */
#ifndef FILTERDEF_H
#define FILTERDEF_H

#define	FILTER_MEAN			0
#define	FILTER_MEADIAN		1
#define	FILTER_GAUSSIAN		2
#define	FILTER_UNSHARP		3
#define	FILTER_SOBEL		4
#define	FILTER_SIEVE		5
#define	FILTER_COLLAPSE		6
#define	FILTER_INVERT		7
#define	FILTER_THRESHOLD	8
#define	FILTER_BINARIZE		9
#define	FILTER_DILATE		10
#define	FILTER_ERODE		11
#define	FILTER_COPY			12
#define	FILTER_SETOPERATOR	13
#define	FILTER_STRETCH		14
#define	FILTER_EQUALIZE		15
#define	FILTER_FLOODFILL	16
#define	FILTER_SMOOTHDIL	17
#define FILTER_ADD			18
#define FILTER_ARITHM		19
#define	FILTER_REPLACE		20
#define	FILTER_CLEAR		21
#define FILTER_OPEN			22
#define	FILTER_CLOSE		23
#define	FILTER_MAXFLOW		24
#define	FILTER_PERONAMALIK	25
#define	FILTER_ROLLINGBALL	26
#define	FILTER_SWAP			27
#define	FILTER_COUNT		28
#define	FILTER_BILATERAL	29

#define	FILTER_GPUMEADIAN		30
#define	FILTER_GPUGAUSSIAN		31
#define	FILTER_GPUPERONAMALIK	32
#define	FILTER_GPUDILATE		33
#define	FILTER_GPUERODE			34
#define	FILTER_GPUSMOOTHDIL		35
#define FILTER_GPUMEDIAN		36
#define FILTER_GPUBILATERAL		37

#endif //FILTERDEF_H
